site_name: Random Wire! 
pages:
- Home: index.md
- Tutorials:
    - Blink: tutorials/blink/blink.md   
    - Document Projects: tutorials/document.md
    - HiCat Livera Docs:
       - Documentation: livera/index.md
       - API Guide: livera/api.md
       - Robot Assembily Guide: livera/robotAssemGuide.md
    - TI Launchpad Resources: tutorials/TI/resources.md
    - ESP-MESH Board: tutorials/ESP-MESH/ESP-MESH.md
- Projects:
    - Arduino:
        - Chatter Bot: projects/arduino/chatterbot.md
        - 4x4 Keypad Matrix: projects/arduino/arduino-project-4x4-keypad-matrix-rotary-encoder/README.md
        - Arduino VGA: projects/arduino/arduino-project-arduino-vga-out/README.md
        - BMP180 Sensor: projects/arduino/arduino-project-bmp180-digital-barometric-pressur/README.md
        - FS1000a 433mhz Transmitters: projects/arduino/arduino-project-fs1000a-433mhz-transmitters/README.md
        - HC-05 Bluetooth: projects/arduino/arduino-project-hc-05-bluetooth-device/README.md
        - Magnetic Reed Switch Water Sensor: projects/arduino/arduino-project-magnetic-reed-switch-water-sensor/README.md
        - Mifare RFID reader RC522: projects/arduino/arduino-project-mifare-rfid-reader-rc522/README.md
        - Nokia 5110 LCD: projects/arduino/arduino-project-nokia-5110-lcd/README.md
        - Pin Control over Ethernet w/OLED: projects/arduino/arduino-project-pin-control-over-ethernet-oled-de/README.md
        - Skynet IM: projects/arduino/arduino-project-skynet-im/README.md
        - SPO-512 Speech Synthesizer: projects/arduino/arduino-project-the-spo-512-speech-synthesizer/README.md  
        - QVGA Display: projects/arduino/QVGA-DISPLAY/QVGA-Display2.md      
    - ESP8266:
        - Temp: projects/esp8266/index.md
    - ESP32:
        - Temp: projects/esp32/index.md
    - TI LaunchPad:
        - TI Launchpad MS432 Multi-Task Demo: projects/TILaunchPad/ti-multi-task/README.md
    - Raspberry PI:
        - Temp: projects/esp32/index.md
    - Other Projects:
        - Hot Wheels 10.524Ghz Radar Gun: projects/other/project-hot-wheels-10-525ghz-radar-gun/README.md
- Robot Projects:
    - Robot Chassis Kits:
        - Actobotics: projects/robot/chassis-kits/Actobotics.md
    - Hero Jr Robot: 
        - Hero Jr Project: projects/robot/herojr.md
        - Hero Jr Star Wars Day Dec 2015: 
            - General Info: projects/robot/HeroJr-StarWarsDay/README.md
            - Midpointe Library Dec 12 Demo: projects/robot/HeroJr-StarWarsDay/Demo.md
            - Outline of Program: projects/robot/HeroJr-StarWarsDay/Outline_Script_for_Star_Wars_Day_Hero_Jr.md
            - Punch List: projects/robot/HeroJr-StarWarsDay/Star_Wars_Hero_Jr_Punch_List.md
            - Pictures: projects/robot/HeroJr-StarWarsDay/pictures_from_Star_Wars_Day.md
    - 2W & 4W Robots:
        - Getting Started: tutorials/robots/robotstart.md
        - L298 Motor Driver: projects/robot/L298MotorDrive/README.md
        - BittyBot: projects/robot/BittyBot.md
        - BittyBot 2: projects/robot/BittyBot2Library.md
        - Compact Rover: projects/robot/CompactRoverLibrary.md
    - Robot Indoor Navigation using RFID: projects/robot/RobotNavigationusingRFID.md
- Ham Radio:
    - MMDVM Hotspot Info: hamradio/hotspot.md
- Other:
    - Sherlock Holmes: index.md    
    - Pen and Paper RPG Games: index.md
    - Movies/TV Shows & OTR: 
        - X Minus One: index.md
        - The Orville: index.md
        - Forbidden Planet (C-57D): index.md
    - DC Comics: index.md
    - Lord of the Rings: index.md
    - Noris Methology: index.md
    - More Stuff: index.md    
- About Me: leroy.md
extra: 
    version: 1.0.2
strict: false
